#pragma once

// Generated by tool-of-rei/test/final_calibration/generate_p4_asset.py.
// Do not hand-edit; regenerate only from a frozen fit and passing M6 holdout.

#include <array>

#include "frequency_response_compensation.hpp"

namespace cyclescope::generated_calibration {

inline constexpr char kIdentitySha256[] = "c5dcde41b09fb2b474504fcf84f6e22d68b33d2c4c97557407d2c31f30e43945";
inline constexpr char kResponseCsvSha256[] = "9d1aace37d65d82a7d3b1ff585ae95459a58e6cf90ece5030f7c313d80781c5f";

inline constexpr std::array<FrequencyResponseAnchor, 12> kResponseAnchors = {{
    {10000.0F, 261.408752405F},
    {10500.0F, 261.450493823F},
    {20000.0F, 261.375206643F},
    {50000.0F, 261.72736568F},
    {100000.0F, 261.106272696F},
    {200000.0F, 263.571409064F},
    {300000.0F, 263.870611229F},
    {400000.0F, 264.198574032F},
    {450000.0F, 265.008275134F},
    {475000.0F, 265.128774271F},
    {490000.0F, 265.212765832F},
    {500000.0F, 265.269494304F},
}};

inline constexpr FrequencyResponseProfile kResponseProfile = {
    .profile_id = 0xC5DCDE41U,
    .upstream = {
        .calibration_id = 25030U,
        .scale_uv_per_lsb = 516U,
        .offset_uv = -6761,
        .filter_profile = 1U,
        .sample_rate_hz = 4062500U,
        .frame_sample_count = 8192U,
    },
    .anchors = kResponseAnchors.data(),
    .anchor_count = kResponseAnchors.size(),
};

}  // namespace cyclescope::generated_calibration
