#pragma once

#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    CYCLESCOPE_DISPLAY_FAIL_NONE = 0,
    CYCLESCOPE_DISPLAY_FAIL_AFTER_BSP_DISPLAY,
    CYCLESCOPE_DISPLAY_FAIL_AFTER_ADAPTER_INIT,
    CYCLESCOPE_DISPLAY_FAIL_AFTER_DISPLAY_REGISTER,
    CYCLESCOPE_DISPLAY_FAIL_AFTER_BSP_TOUCH,
    CYCLESCOPE_DISPLAY_FAIL_AFTER_TOUCH_REGISTER,
    CYCLESCOPE_DISPLAY_FAIL_AFTER_WORKER_START,
    CYCLESCOPE_DISPLAY_FAIL_AFTER_BACKLIGHT_ON,
    CYCLESCOPE_DISPLAY_FAIL_COUNT,
} cyclescope_display_lifecycle_failpoint_t;

typedef enum {
    CYCLESCOPE_DISPLAY_LIFECYCLE_BSP_DISPLAY_CREATED = 0,
    CYCLESCOPE_DISPLAY_LIFECYCLE_ADAPTER_INITIALIZED,
    CYCLESCOPE_DISPLAY_LIFECYCLE_DISPLAY_REGISTERED,
    CYCLESCOPE_DISPLAY_LIFECYCLE_BSP_TOUCH_CREATED,
    CYCLESCOPE_DISPLAY_LIFECYCLE_TOUCH_REGISTERED,
    CYCLESCOPE_DISPLAY_LIFECYCLE_WORKER_STARTED,
    CYCLESCOPE_DISPLAY_LIFECYCLE_BACKLIGHT_ON,
    CYCLESCOPE_DISPLAY_LIFECYCLE_FAULT_CONSUMED,
    CYCLESCOPE_DISPLAY_LIFECYCLE_BACKLIGHT_OFF,
    CYCLESCOPE_DISPLAY_LIFECYCLE_TOUCH_UNREGISTERED,
    CYCLESCOPE_DISPLAY_LIFECYCLE_DISPLAY_UNREGISTERED,
    CYCLESCOPE_DISPLAY_LIFECYCLE_ADAPTER_DEINITIALIZED,
    CYCLESCOPE_DISPLAY_LIFECYCLE_RAW_TOUCH_DELETED,
    CYCLESCOPE_DISPLAY_LIFECYCLE_BSP_TOUCH_DELETED,
    CYCLESCOPE_DISPLAY_LIFECYCLE_I2C_DEINITIALIZED,
    CYCLESCOPE_DISPLAY_LIFECYCLE_PANEL_DMA2D_DISABLED,
    CYCLESCOPE_DISPLAY_LIFECYCLE_BACKLIGHT_CHANNEL_DECONFIGURED,
    CYCLESCOPE_DISPLAY_LIFECYCLE_BSP_DISPLAY_DELETED,
} cyclescope_display_lifecycle_event_t;

bool cyclescope_display_lifecycle_consume_failpoint(
    cyclescope_display_lifecycle_failpoint_t point);
void cyclescope_display_lifecycle_note_event(
    cyclescope_display_lifecycle_event_t event);

#ifdef __cplusplus
}
#endif
