#!/usr/bin/env python3
"""Generate the immutable ESP32-P4 response profile after M6 passes.

The generator refuses drafts, failed/tampered holdout reports, changed anchor
sets, or any upstream identity other than the one frozen by this campaign.
It never reads instrument or network state.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
from pathlib import Path
import shutil
from typing import Any

import calibration_core as core


HEADER_NAME = "frequency_response_profile_generated.hpp"


def _read_response_rows(path: Path) -> list[dict[str, float]]:
    with path.open("r", encoding="utf-8", newline="") as stream:
        raw_rows = [dict(row) for row in csv.DictReader(stream)]
    rows: list[dict[str, float]] = []
    for raw in raw_rows:
        try:
            frequency_hz = float(raw["frequency_hz"])
            input_uv_per_code = float(raw["input_uv_per_code"])
        except (KeyError, TypeError, ValueError) as error:
            raise core.CalibrationError("response.csv row is malformed") from error
        if (
            not math.isfinite(frequency_hz)
            or not math.isfinite(input_uv_per_code)
            or frequency_hz <= 0.0
            or input_uv_per_code <= 0.0
        ):
            raise core.CalibrationError("response.csv contains non-finite/non-positive data")
        rows.append(
            {
                "frequency_hz": frequency_hz,
                "input_uv_per_code": input_uv_per_code,
            }
        )
    expected = [float(value) for value in core.TRAIN_FREQUENCIES_HZ]
    if [row["frequency_hz"] for row in rows] != expected:
        raise core.CalibrationError("response.csv anchor set is not the frozen 12 points")
    return rows


def _cpp_float(value: float) -> str:
    rendered = f"{value:.9f}".rstrip("0").rstrip(".")
    if "." not in rendered:
        rendered += ".0"
    return rendered + "F"


def render_header(
    *,
    profile_id: int,
    identity_sha256: str,
    response_sha256: str,
    rows: list[dict[str, float]],
    upstream: dict[str, int],
) -> str:
    if profile_id <= 0 or profile_id > 0xFFFFFFFF:
        raise core.CalibrationError("P4 response profile ID is outside uint32")
    for digest in (identity_sha256, response_sha256):
        if len(digest) != 64 or any(character not in "0123456789abcdef" for character in digest):
            raise core.CalibrationError("calibration digest is not lowercase SHA-256")
    anchors = "\n".join(
        "    {"
        + _cpp_float(row["frequency_hz"])
        + ", "
        + _cpp_float(row["input_uv_per_code"])
        + "},"
        for row in rows
    )
    return f"""#pragma once

// Generated by tool-of-rei/test/final_calibration/generate_p4_asset.py.
// Do not hand-edit; regenerate only from a frozen fit and passing M6 holdout.

#include <array>

#include "frequency_response_compensation.hpp"

namespace cyclescope::generated_calibration {{

inline constexpr char kIdentitySha256[] = "{identity_sha256}";
inline constexpr char kResponseCsvSha256[] = "{response_sha256}";

inline constexpr std::array<FrequencyResponseAnchor, {len(rows)}> kResponseAnchors = {{{{
{anchors}
}}}};

inline constexpr FrequencyResponseProfile kResponseProfile = {{
    .profile_id = 0x{profile_id:08X}U,
    .upstream = {{
        .calibration_id = {upstream['calibration_id']}U,
        .scale_uv_per_lsb = {upstream['scale_uv_per_lsb']}U,
        .offset_uv = {upstream['offset_uv']},
        .filter_profile = {upstream['filter_profile']}U,
        .sample_rate_hz = {upstream['sample_rate_hz']}U,
        .frame_sample_count = {upstream['frame_sample_count']}U,
    }},
    .anchors = kResponseAnchors.data(),
    .anchor_count = kResponseAnchors.size(),
}};

}}  // namespace cyclescope::generated_calibration
"""


def generate_asset(
    fit_dir: Path,
    holdout_dir: Path,
    output_dir: Path,
    *,
    install_header: Path | None = None,
) -> dict[str, Any]:
    fit_dir = fit_dir.resolve()
    holdout_dir = holdout_dir.resolve()
    output_dir = output_dir.resolve()
    if output_dir.exists():
        raise core.CalibrationError(f"P4 asset output already exists: {output_dir}")
    fit_audit = core.verify_sha256s(fit_dir)
    holdout_audit = core.verify_sha256s(holdout_dir)
    calibration = core.read_json(fit_dir / "calibration.json")
    build_manifest = core.read_json(fit_dir / "calibration-build-manifest.json")
    holdout = core.read_json(holdout_dir / "holdout-report.json")

    if calibration.get("status") != "fit-frozen-before-holdout":
        raise core.CalibrationError("P4 asset requires a frozen pre-holdout fit")
    if (
        holdout.get("pass") is not True
        or holdout.get("hard_5mv_1khz_pass") is not True
        or holdout.get("fit_frozen_before_holdout") is not True
        or holdout.get("holdout_refit_performed") is not False
    ):
        raise core.CalibrationError("P4 asset requires an untampered passing M6 holdout")
    profile_id = int(calibration.get("p4_response_profile_id", 0))
    if (
        profile_id == 0
        or int(build_manifest.get("p4_response_profile_id", 0)) != profile_id
        or int(holdout.get("p4_response_profile_id", 0)) != profile_id
    ):
        raise core.CalibrationError("P4 profile ID differs across fit/holdout artifacts")
    upstream = calibration.get("upstream_identity")
    if upstream != core.UPSTREAM_IDENTITY or build_manifest.get("upstream_identity") != core.UPSTREAM_IDENTITY:
        raise core.CalibrationError("P4 asset upstream identity is not the frozen six-field identity")
    scope_binding = calibration.get("scope_amendment")
    if (
        not isinstance(scope_binding, dict)
        or scope_binding.get("version") != 2
        or scope_binding.get("supported_source_max_vpp_v")
        != core.SUPPORTED_SOURCE_MAX_VPP_V
        or scope_binding.get("excluded_case_ids")
        != list(core.EXCLUDED_COMPRESSED_CASE_IDS)
        or build_manifest.get("scope_amendment") != scope_binding
        or holdout.get("scope_amendment") != scope_binding
    ):
        raise core.CalibrationError(
            "P4 asset scope amendment differs across fit/holdout artifacts"
        )

    response_path = fit_dir / "response.csv"
    response_sha256 = core.sha256_file(response_path)
    response_manifest = build_manifest.get("response_csv")
    if (
        not isinstance(response_manifest, dict)
        or response_manifest.get("path") != "response.csv"
        or response_manifest.get("sha256") != response_sha256
    ):
        raise core.CalibrationError("response.csv SHA is not bound by the fit manifest")
    identity_sha256 = str(calibration.get("identity_sha256", ""))
    if build_manifest.get("identity_sha256") != identity_sha256:
        raise core.CalibrationError("identity SHA differs across fit artifacts")

    rows = _read_response_rows(response_path)
    header_text = render_header(
        profile_id=profile_id,
        identity_sha256=identity_sha256,
        response_sha256=response_sha256,
        rows=rows,
        upstream={key: int(value) for key, value in upstream.items()},
    )
    output_dir.mkdir(parents=True, exist_ok=False)
    package_header = output_dir / HEADER_NAME
    package_header.write_text(header_text, encoding="utf-8")
    installed_path: str | None = None
    if install_header is not None:
        install_header = install_header.resolve()
        install_header.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(package_header, install_header)
        installed_path = str(install_header)

    manifest = {
        "format": "CycleScope generated P4 frequency-response asset v1",
        "p4_response_profile_id": profile_id,
        "identity_sha256": identity_sha256,
        "response_csv_sha256": response_sha256,
        "upstream_identity": dict(upstream),
        "scope_amendment": scope_binding,
        "anchor_count": len(rows),
        "holdout_hard_gate_pass": True,
        "holdout_target_gate_pass": bool(holdout.get("target_3mv_500hz_pass")),
        "fit_sha256s_manifest": fit_audit["manifest_sha256"],
        "holdout_sha256s_manifest": holdout_audit["manifest_sha256"],
        "generated_header": {
            "path": HEADER_NAME,
            "sha256": core.sha256_file(package_header),
        },
        "installed_header": installed_path,
        "fpga_changes_required": False,
    }
    core.write_json(output_dir / "p4-asset-manifest.json", manifest)
    core.write_sha256s(output_dir)
    return manifest


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--fit-dir", type=Path, required=True)
    parser.add_argument("--holdout-dir", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--install-header", type=Path)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    manifest = generate_asset(
        args.fit_dir,
        args.holdout_dir,
        args.output_dir,
        install_header=args.install_header,
    )
    print(json.dumps(manifest, indent=2, sort_keys=True, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
